### PR TITLE
feat: Skip cloning if using --rebase-remotely

### PR DESCRIPTION
**Pull request by slovdahl**
Thanks to the original author of this, @csymeonides-mf. Let's aim for upstreaming this too if someone ever picks up maintenance of the upstream repo .

### CODE REVIEW

**Comment by perlun** [comment]
(I rebased this now to let CI run)

**Comment by perlun** [comment]
> Let's aim for upstreaming this too if someone ever picks up maintenance of the upstream repo .

Just checking: this won't affect our own (Hibox) usage of the tool, since we use local rebasing, right? :thinking:

**Comment by slovdahl** [comment]
> > Let's aim for upstreaming this too if someone ever picks up maintenance of the upstream repo .
> 
> Just checking: this won't affect our own (Hibox) usage of the tool, since we use local rebasing, right? thinking

It will, otherwise I would not have included it :grin: 

```shell
$ grep rebase-remotely marge-bot-config.yaml 
rebase-remotely: true
```

**Comment by perlun** [comment]
> It will, otherwise I would not have included it grin

Ah, I see. But will that work with the commit message trailers we have configured? :thinking: Perhaps it will, because GitLab takes care of it itself?

Seems like a good fix though, since this will save **a lot** of disk space for some use cases (like ours).

**Review by perlun — APPROVED** [review]

**Comment by slovdahl** [comment]
All Marge does for us is through the GitLab API, so as far as I understand it the cloning etc is totally redundant.

**Comment by csymeonides-mf** [comment]
> Seems like a good fix though, since this will save **a lot** of disk space for some use cases (like ours).

and time!

**Pull request merged**
