### PR TITLE
(github) Remove deployment workflow

### PR DESCRIPTION
**Pull request by perlun**
Should no longer be active now: https://github.com/hiboxsystems/marge-bot/pull/4/files#r1054065985

### CODE REVIEW

**Comment by slovdahl** [comment]
I was thinking that we can keep it and change the repository reference once we intend to publish an image to Docker Hub. :thinking:

**Comment by perlun** [comment]
> I was thinking that we can keep it and change the repository reference once we intend to publish an image to Docker Hub. thinking

Works for me, but it runs on each `master` commit right now since I enabled the GitHub Actions for this repo. :thinking: Should we just edit the branch name (in the `.yml` file) to disable it right now perhaps?

**Comment by slovdahl** [comment]
Hm.. So this check doesn't work? :thinking: 

```yaml
    if: ${{ github.repository == 'smarkets/marge-bot' }}  # Only run from main repo
```

**Comment by perlun** [comment]
> Hm.. So this check doesn't work? thinking
> 
> ```yaml
>     if: ${{ github.repository == 'smarkets/marge-bot' }}  # Only run from main repo
> ```

Ah.... I think I may have missed that one. :sweat_smile: :man_facepalming:

**Pull request closed without merging**
